### ISSUE TITLE
Add port of Snabby

### ISSUE THREAD

**Issue by buntec** [buntec/scala-js-snabbdom#4]
[snabby](https://github.com/mreinstein/snabby) is a useful companion to Snabbdom that allows you to parse literal HTML strings to vnodes.

Snabby in turn depends on [hyperx](https://github.com/mreinstein/hyperx), which would then also need to be ported.

I've used Snabby in ff4s to support literals for things like SVG icons, so this would be required to remove all JS dependencies.

**Comment by armanbilge** [comment]
https://github.com/buntec/scala-js-snabbdom/pull/23 along with `node.innerHTML = "..."` makes it possible to parse literal HTML strings to `VNode`s.

Supporting templating/interpolating of HTML strings falls out-of-scope of this library IMO, and I think would be best implemented on top of scala-dom-types anyway since it's not specific to vdom.
